---
- hosts: all
  remote_user: root
  tasks:
  - name: Add Yum repo (aliyun-base)
    yum_repository:
      name: aliyun-base
      description: CentOS-7 - Base - mirrors.aliyun.com
      failovermethod: priority
      baseurl: http://mirrors.aliyun.com/centos/7/os/$basearch/
      gpgcheck: 1
      gpgkey: http://mirrors.aliyun.com/centos/RPM-GPG-KEY-CentOS-7
  - name: Add Yum repo (aliyun-updates)
    yum_repository:
      name: aliyun-updates
      description: CentOS-7 - Updates - mirrors.aliyun.com
      failovermethod: priority
      baseurl: http://mirrors.aliyun.com/centos/7/updates/$basearch/
      gpgcheck: 1
      gpgkey: http://mirrors.aliyun.com/centos/RPM-GPG-KEY-CentOS-7
  - name: Add Yum repo (aliyun-extras)
    yum_repository:
      name: aliyun-extras
      description: CentOS-7 - Extras - mirrors.aliyun.com
      failovermethod: priority
      baseurl: http://mirrors.aliyun.com/centos/7/extras/$basearch/
      gpgcheck: 1
      gpgkey: http://mirrors.aliyun.com/centos/RPM-GPG-KEY-CentOS-7
  - name: Add Yum repo (aliyun-centosplus)
    yum_repository:
      name: aliyun-centosplus
      description: CentOS-7 - Plus - mirrors.aliyun.com
      failovermethod: priority
      baseurl: http://mirrors.aliyun.com/centos/7/centosplus/$basearch/
      gpgcheck: 1
      enabled: 0
      gpgkey: http://mirrors.aliyun.com/centos/RPM-GPG-KEY-CentOS-7
  - name: Add Yum repo (aliyun-contrib)
    yum_repository:
      name: aliyun-contrib
      description: CentOS-7 - Contrib - mirrors.aliyun.com
      failovermethod: priority
      baseurl: http://mirrors.aliyun.com/centos/7/contrib/$basearch/
      gpgcheck: 1
      enabled: 0
      gpgkey: http://mirrors.aliyun.com/centos/RPM-GPG-KEY-CentOS-7

