apiVersion: v1
kind: Service
metadata:
  name: base-mall-api-${CICD_GIT_BRANCH}-service
  namespace: default
  labels:
    app: base-mall-api-${CICD_GIT_BRANCH}-service
spec:
  selector:
    app: base-mall-api-${CICD_GIT_BRANCH}
  type: NodePort
  ports:
    - name: http
      # 节点暴露的端口， 每个环境更换
      nodePort: 30065
      protocol: TCP
      port: 6060
      targetPort: 6060
    - name: ws
      # 节点暴露的端口， 每个环境更换
      nodePort: 30066
      protocol: TCP
      port: 6062
      targetPort: 6062

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-mall-api-${CICD_GIT_BRANCH}
  namespace: default
  labels:
    app: base-mall-api-${CICD_GIT_BRANCH}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: base-mall-api-${CICD_GIT_BRANCH}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: base-mall-api-${CICD_GIT_BRANCH}
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: maven
          # pipline步骤里面打好的镜像
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          imagePullPolicy: Always
          ports:
            - containerPort: 6060
            - containerPort: 6062
          # 就绪探针
          readinessProbe:
            httpGet:
              path: /mall/actuator/health/readiness
              port: 6060
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 6
          # 存活探针
          livenessProbe:
            httpGet:
              path: /mall/actuator/health/liveness
              port: 6060
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 6